### ISSUE TITLE
what is Rho？

### ISSUE THREAD

**Issue by LeightonQian417** [SIJIEJI/CLNet#2]
I run this code on my pycharm on Win10, there are some bug occurs.
to fit my gpu cuda version, I install pytorch1.8.0, there are some different function from your original verion.
For example, the fft function 
![image](https://user-images.githubusercontent.com/34114370/146190109-78062796-eacd-480f-997b-e4dbb25983d7.png)
I've modified it like the picture shows.
but got a result bellow:
![image](https://user-images.githubusercontent.com/34114370/146190301-923541fe-423f-446d-8183-ef1f76f96c13.png)
rho is nan, I cant understand what the meaning of rho? does it matter when i cant get it?

**Comment by SIJIEJI** [comment]
Hi, the rho actually succeeded from the first paper, CSINet. It doesn't matter as we didn't compare rho in the paper.

**Comment by LeightonQian417** [comment]
> 

OK,I understand! thanks for your reply!
