### ISSUE TITLE
NMSE计算请教

### ISSUE THREAD

**Issue by JackokieZhao** [SIJIEJI/CLNet#4]
你好，想请教一下代码中NMSE和rho计算的问题：
（1） 请问在训练中使用的信道应该都是经过二维FFT之后并进行归一化的信道吧？
如果是这样的话，原始的信道应该是需要降信道进行二维的IFFT2，但是您的代码中为什么是进行1维的FFT呢？这里我不太明白。
（2） 如果说FFT和IFFT2是等效的话，那么为什么频域变换成257维，然后又只取其中的125维呢？这里也不太清楚。

**Comment by sjyong8989** [comment]
抱歉时隔这么久突然评论。我也遇到同样的问题，请问你现在解决了吗？
