### ISSUE TITLE
Model Flops

### ISSUE THREAD

**Issue by CQIITLAB** [SIJIEJI/CLNet#5]
Hello, great work!
I tried to run your code, where the Model Flops is 5.702M. However, it's 4.05M in your paper. Why??? Thank you very much!

**Comment by SIJIEJI** [comment]
> 
As per README stated:
"The flops reported in the paper are caculated by fvcore to align with other SOTA works. The fvcore caculator didn't count the BN layer in, therefore it's less than thop." 
As long as you use the same calculator to calculate the flops between different frameworks, it's fine.
